version: "3.8"

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.6.0
    environment:
      - discovery.type=single-node
      - ingest.geoip.downloader.enabled=false
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic
    volumes:
      - elastic:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    image: kibana:8.6.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elastic
    volumes:
      - elastic:/usr/share/kibana/data
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601


volumes:
  elastic:
    external: true

networks:
  elastic:
    external: true