version: "3.8"

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.1
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ingest.geoip.downloader.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic
    volumes:
      - elastic:/usr/share/elasticsearch/data


volumes:
  elastic:
    external: true

networks:
  elastic:
    external: true